version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 5173:5173
    working_dir: /app-frontend
    depends_on:
      - backend
  backend:
    container_name: app_backend
    build: ./backend
    entrypoint: sh -c "npm install && npm run start:dev"
    ports:
      - 3001:3001
    working_dir: /app-backend
    environment:
      - APP_PORT=3001
      - JWT_SECRET=NGCA$$$HH
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:10.4
    ports:
      - 5441:5441
    environment:
      - PGDATABASE=ng_challenge
      - PGUSER=postgres
      - PGPASSWORD=postgres
    restart: 'always'
